config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Marketing
  # Defines the root path route ("/")
  root to: "home#index"
  get "alpha_announcement" => "home#alpha_announcement", :as => :alpha_announcement
  get "learn-more" => "home#learn_more", :as => :learn_more
  get "privacy-policy" => "home#privacy_policy", :as => :privacy_policy
  get "tos" => "home#tos", :as => :tos

  # Authentication
  resource :login, only: [:new, :show, :create, :destroy]
  resource :login_request, only: [:show]
  resource :one_time_password, only: [:new]
  resource :temporary_code_login, only: [:new, :create]

  # Invites
  resources :invites, only: [:new, :create, :destroy]
  resource :accept_invite, only: [:show]

  # Admin
  get "admin" => "admin#index", :as => :admin
  namespace :admin do
    resources :users
    resources :players
    resources :teams
    resources :invoices
    resources :orders
    resources :problems
    resources :impersonations, only: [:create, :destroy]
  end

  # Game
  resources :players
  resources :problems, only: [:show]
  resource :responses, only: [:create, :new], path: "game"
  resources :sessions, only: [:create, :destroy]
  resources :scores, only: [:show]
  resources :users, only: [:destroy]
  resources :trial_memberships, only: [:create]

  # Settings
  resource :team, only: [:show, :edit, :update]
  resource :profile, only: [:show, :edit, :update]

  # Stripe
  resources :orders, only: [:new]
  get "success" => "checkout_successes#show"
  post "webhook" => "webhooks#create"
end

app/models/player.rb
# typed: strict

# A player of the game.
class Player < ApplicationRecord
  extend T::Sig

  include Logable
  include Teamable

  has_many :responses, dependent: :destroy
  has_many :player_problem_aggregates, dependent: :destroy

  sig { returns(T::Boolean) }
  def has_played?
    responses.exists?
  end

  sig { returns(T::Boolean) }
  def was_just_wrong?
    return false unless has_played?

    last_response = T.let(responses.last, Response)
    !last_response.correct && T.let(Time.at(last_response.completed_at), Time) >= T.let(30.seconds, ActiveSupport::Duration).ago
  end

  sig { returns(String) }
  def display
    T.must(name)
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < AdminBaseController
  def index
    @players = Player.includes(:team).order(created_at: :desc)
  end

  def show
    @player = Player.find_by(id: params[:id])
    session[:player_id] = @player.id
    @active_problem_groups = Commands::GetActiveProblemGroupings.call(player: @player)
    @retired_problem_groups = Commands::GetRetiredProblemGroupings.call(player: @player)
    @score = Commands::GetPlayerScore.call(player: @player)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    if Commands::IsFirstTimeUser.call(user: @current_user, request: request)
      @notification = Notification.new(title: "Welcome! Click the 'Add player' button.", description: "The player is the person who will be playing the game. You can add as many players as you like.")
    end
    @players = user_players
    session[:player_id] = nil
  end

  def show
    # TODO this is likely not perfomant and we should consider a better approach
    @player = user_player

    if @player.nil?
      Rails.logger.error(
        "Player not found",
        player_id: params[:id],
        user_id: @current_user.id,
        team_id: @current_user.team_id,
        team_name: @current_user.team.name,
        params: params
      )
      flash[:error] = "Player not found"
      redirect_to players_path
    end

    session[:player_id] = @player.id
    if Commands::IsFirstTimeUser.call(user: @current_user, request: request)
      @notification = Notification.new(title: "Click 'Play' to start practicing.", description: "If you haven't done so already, make sure #{@player.name} is holding your phone or is at the keyboard.")
    end
    @active_problem_groups = Commands::GetActiveProblemGroupings.call(player: @player)
    @retired_problem_groups = Commands::GetRetiredProblemGroupings.call(player: @player)
    @score = Commands::GetPlayerScore.call(player: @player)
  end

  def new
    @player = Player.new(team: @current_user.team)
  end

  def create
    @player = Commands::CreatePlayer.call(input: player_params)
    redirect_to player_path(@player), notice: "Player #{@player.name} created."
  end

  def edit
    @player = user_player
  end

  def update
    result = Commands::UpdatePlayer.call(player: user_player, input: player_params)

    if result.success
      redirect_to player_path(result.player), notice: "Player #{result.player.name} updated."
    else
      redirect_to player_path(user_player), error: "Player #{user_player.name} could not be updated. #{result.error}"
    end
  end

  def destroy
    @player = user_player
    @player.destroy
    redirect_to players_path, notice: "Player #{@player.name} removed."
  end

  private

  def player_params
    params.require(:player).permit(:name, :level).merge(team_id: @current_user.team_id)
  end

  def user_players
    Commands::GetUserPlayers.call(user: @current_user)
  end

  def user_player
    user_players.find_by(id: params[:id])
  end
end

app/views/admin/players/index.html.erb
<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
    <%= render(FormHeaderComponent.new(title: "Players", description: "A list of all players in the app.", subtitle: "Admin")) %>
  </div>
</div>
<div class="mt-8 flow-root">
  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <table class="min-w-full divide-y divide-gray-300">
        <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Team</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Problems solved</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Consecutive days played</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Created</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @players.each do |player| %>
            <tr>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                <%= link_to player.name, admin_player_path(player) %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= player.team.name %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= Commands::GetTotalProblemsSolved.call(player: player).problems_solved %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= Commands::GetConsecutiveDaysPlayed.call(player: player) %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= time_ago_in_words(player.created_at) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/players/show.html.erb
<div class="mt-8 px-4 sm:px-6 lg:px-8">
  <%= render "shared/header_with_primary_secondary_buttons", title: @player.name, subtitle: "Player", description: "All about the progress of #{@player.name}", secondary_text: "Edit", secondary_path: edit_player_path(@player), primary_text: "Play", primary_path: sessions_path(player_id: @player.id), button: true %>
  <%= render "scores/summary", score: @score, name: @player.name  %>
  <div class="pb-5 my-5">
    <div class="sm:flex sm:items-baseline sm:justify-between">
      <div class="sm:w-0 sm:flex-1">
        <div class="flex justify-start gap-2">
          <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Active</span>
          <h1 id="message-heading" class="text-base font-semibold leading-6 text-gray-900">Problems</h1>
        </div>
        <p class="mt-1 truncate text-sm text-gray-500">
          <%= "#{@player.name}'s current practice problems" %>
        </p>
      </div>
    </div>
  </div>
  <div class="grid grid-cols-3 gap-3 mb-5">
    <% @active_problem_groups.each do |grouping| %>
      <div class="overflow-hidden rounded-lg bg-white shadow">
        <div class="px-4 py-5 sm:p-6 grid lg:grid-cols-5 gap-3">
          <% grouping.each do |player_problem| %>
            <%= link_to score_path(player_problem.problem.id) do %>
              <% if player_problem.color == 'red' %>
                <%= render "shared/problem_bubble", text: player_problem.display, color: "red" %>
              <% elsif player_problem.color == 'yellow' %>
                <%= render "shared/problem_bubble", text: player_problem.display, color: "yellow" %>
              <% elsif player_problem.color == 'green' %>
                <%= render "shared/problem_bubble", text: player_problem.display, color: "green" %>
              <% else %>
                <%= render "shared/problem_bubble", text: player_problem.display, color: "gray" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% if @retired_problem_groups.present? %>
    <div class="pb-5 my-5">
      <div class="sm:flex sm:items-baseline sm:justify-between">
        <div class="sm:w-0 sm:flex-1">
          <div class="flex justify-start gap-2">
            <span class="inline-flex items-center rounded-md bg-cyan-50 px-2 py-1 text-xs font-medium text-cyan-700 ring-1 ring-inset ring-cyan-600/20">Completed</span>
            <h1 id="message-heading" class="text-base font-semibold leading-6 text-gray-900">Problems</h1>
          </div>
          <p class="mt-1 truncate text-sm text-gray-500">
            <%= "#{@player.name}'s retired practice problems" %>
          </p>
        </div>
      </div>
    </div>
    <div class="grid grid-cols-3 gap-3 mb-5">
      <% @retired_problem_groups.each do |grouping| %>
        <div class="overflow-hidden rounded-lg bg-white shadow">
          <div class="px-4 sm:px-6">
            <div class="border-b border-gray-200 bg-white py-5">
              <h3 class="text-base font-semibold text-gray-900">
                Level: <%= grouping.first.level %>
              </h3>
              <p class="mt-1 text-sm text-gray-500">
                <%= grouping.count %> problems
              </p>
            </div>
          </div>
          <div class="px-4 py-5 sm:p-6 grid lg:grid-cols-5 gap-3">
            <% grouping.each do |player_problem| %>
              <%= link_to score_path(player_problem.problem.id) do %>
                <% if player_problem.color == 'red' %>
                  <%= render "shared/problem_bubble", text: player_problem.display, color: "red" %>
                <% elsif player_problem.color == 'yellow' %>
                  <%= render "shared/problem_bubble", text: player_problem.display, color: "yellow" %>
                <% elsif player_problem.color == 'green' %>
                  <%= render "shared/problem_bubble", text: player_problem.display, color: "green" %>
                <% else %>
                  <%= render "shared/problem_bubble", text: player_problem.display, color: "gray" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>