config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Marketing
  # Defines the root path route ("/")
  root to: "home#index"
  get "alpha_announcement" => "home#alpha_announcement", :as => :alpha_announcement
  get "learn-more" => "home#learn_more", :as => :learn_more
  get "privacy-policy" => "home#privacy_policy", :as => :privacy_policy
  get "tos" => "home#tos", :as => :tos

  # Authentication
  resource :login, only: [:new, :show, :create, :destroy]
  resource :login_request, only: [:show]
  resource :one_time_password, only: [:new]
  resource :temporary_code_login, only: [:new, :create]

  # Invites
  resources :invites, only: [:new, :create, :destroy]
  resource :accept_invite, only: [:show]

  # Admin
  get "admin" => "admin#index", :as => :admin
  namespace :admin do
    resources :users
    resources :players
    resources :teams
    resources :invoices
    resources :orders
    resources :problems
    resources :impersonations, only: [:create, :destroy]
  end

  # Game
  resources :players
  resources :problems, only: [:show]
  resource :responses, only: [:create, :new], path: "game"
  resources :sessions, only: [:create, :destroy]
  resources :scores, only: [:show]
  resources :users, only: [:destroy]
  resources :trial_memberships, only: [:create]

  # Settings
  resource :team, only: [:show, :edit, :update]
  resource :profile, only: [:show, :edit, :update]

  # Stripe
  resources :orders, only: [:new]
  get "success" => "checkout_successes#show"
  post "webhook" => "webhooks#create"
end

app/models/order.rb
# typed: strict

class Order < ApplicationRecord
  extend T::Sig

  belongs_to :user
  belongs_to :team

  sig { returns(Float) }
  def in_dollars
    amount_total / 100.0
  end

  sig { returns(T::Boolean) }
  def paid?
    payment_status == "paid"
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminBaseController
  def index
    @orders = Order.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  free_loaders_welcome!

  def new
    @path = Commands::CreateStripeCheckoutSession.call(
      email: @current_user.email,
      success_url: success_url,
      cancel_url: new_order_url
    )
  end
end

app/views/admin/orders/index.html.erb
<div class="sm:flex sm:items-center">
  <div class="sm:flex-auto">
    <%= render(FormHeaderComponent.new(title: "Orders", description: "A list of all orders in the app.", subtitle: "Admin")) %>
  </div>
</div>
<div class="mt-8 flow-root">
  <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
      <table class="min-w-full divide-y divide-gray-300">
        <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Order</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">User</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Team</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Amount</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Created</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Invoice</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200">
          <% @orders.each do |order| %>
            <tr>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                <%= link_to order.id, admin_order_path(order) %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= order.user.email %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= order.team.name %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= number_to_currency(order.in_dollars) %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <%= time_ago_in_words(order.created_at) %> ago
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                <% if order.payment_status == 'paid' %>
                  <%= render(SmallBadgeBorderComponent.new(label: order.payment_status, color: Colors::Green)) %>
                <% else %>
                  <%= render(SmallBadgeBorderComponent.new(label: order.payment_status, color: Colors::Red)) %>
                <% end %>
              </td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-cyan-700">
                <%= link_to order.invoice_token, order.hosted_invoice_url %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>