config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Marketing
  # Defines the root path route ("/")
  root to: "home#index"
  get "alpha_announcement" => "home#alpha_announcement", :as => :alpha_announcement
  get "learn-more" => "home#learn_more", :as => :learn_more
  get "privacy-policy" => "home#privacy_policy", :as => :privacy_policy
  get "tos" => "home#tos", :as => :tos

  # Authentication
  resource :login, only: [:new, :show, :create, :destroy]
  resource :login_request, only: [:show]
  resource :one_time_password, only: [:new]
  resource :temporary_code_login, only: [:new, :create]

  # Invites
  resources :invites, only: [:new, :create, :destroy]
  resource :accept_invite, only: [:show]

  # Admin
  get "admin" => "admin#index", :as => :admin
  namespace :admin do
    resources :users
    resources :players
    resources :teams
    resources :invoices
    resources :orders
    resources :problems
    resources :impersonations, only: [:create, :destroy]
  end

  # Game
  resources :players
  resources :problems, only: [:show]
  resource :responses, only: [:create, :new], path: "game"
  resources :sessions, only: [:create, :destroy]
  resources :scores, only: [:show]
  resources :users, only: [:destroy]
  resources :trial_memberships, only: [:create]

  # Settings
  resource :team, only: [:show, :edit, :update]
  resource :profile, only: [:show, :edit, :update]

  # Stripe
  resources :orders, only: [:new]
  get "success" => "checkout_successes#show"
  post "webhook" => "webhooks#create"
end

app/views/shared/_admin_data_bubble.html.erb
<% if value.positive? %>
  <div class="inline-flex items-baseline rounded-full px-2.5 py-0.5 text-sm font-medium bg-green-100 text-green-800 md:mt-2 lg:mt-0">
    <svg class="-ml-1 mr-0.5 h-5 w-5 flex-shrink-0 self-center text-green-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M10 17a.75.75 0 01-.75-.75V5.612L5.29 9.77a.75.75 0 01-1.08-1.04l5.25-5.5a.75.75 0 011.08 0l5.25 5.5a.75.75 0 11-1.08 1.04l-3.96-4.158V16.25A.75.75 0 0110 17z" clip-rule="evenodd" />
    </svg>
    <%= value %>
  </div>
<% else %>
  <div class="inline-flex items-baseline rounded-full px-2.5 py-0.5 text-sm font-medium bg-red-100 text-red-800 md:mt-2 lg:mt-0">
    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="-ml-1 mr-0.5 h-5 w-5 flex-shrink-0 self-center text-red-500">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
    </svg>
    <%= value %>
  </div>
<% end %>

app/views/shared/_cards.html.erb
<div class="grid grid-cols-3 gap-3 mb-5">
  <% groupings.each do |grouping| %>
    <div class="overflow-hidden rounded-lg bg-white shadow">
      <div class="px-4 py-5 sm:p-6">
        <div class="border-b border-gray-200 bg-white py-5 mb-4">
          <h3 class="text-base font-semibold text-gray-900">
            Level: <%= grouping.first %>
          </h3>
          <p class="mt-1 text-sm text-gray-500">
            <%= grouping.last.count %> problems
          </p>
        </div>
        <div class="grid lg:grid-cols-4 gap-3 mb-5 justify-items-center">
          <% grouping.last.each do |item| %>
            <%= render "shared/problem_bubble", text: item, color: "gray" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_email_field.html.erb
<div class="mt-2 grid grid-cols-1 gap-x-6 gap-y-4 sm:grid-cols-6">
  <div class="sm:col-span-3">
    <%= form.label :email, "Email", class: "block text-sm font-medium leading-6 text-gray-900"  %>
    <div class="relative mt-2 rounded-md shadow-sm">
      <% if model&.errors&.any? %>
        <div class="relative mt-2 rounded-md shadow-sm">
          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z" />
              <path d="M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z" />
            </svg>
          </div>
          <%= f.email_field :email, class: "block w-full rounded-md border-0 py-1.5 pl-10 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-cyan-600 sm:text-sm sm:leading-6", placeholder: placeholder %>
          <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
            <svg class="h-5 w-5 text-red-500" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-5a.75.75 0 01.75.75v4.5a.75.75 0 01-1.5 0v-4.5A.75.75 0 0110 5zm0 10a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
            </svg>
          </div>
        </div>
      <% else %>
        <div class="relative mt-2 rounded-md shadow-sm">
          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z" />
              <path d="M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z" />
            </svg>
          </div>
          <%= form.email_field :email, class: "block w-full rounded-md border-0 py-1.5 pl-10 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-cyan-600 sm:text-sm sm:leading-6", placeholder: placeholder %>
        </div>
      <% end %>
    </div>
    <% if model&.errors&.any? %>
      <% model.errors.full_messages.each do |message| %>
        <p class="mt-2 text-sm text-red-600" id="email-error"><%= message %></p>
      <% end %>
    <% else %>
      <p class="mt-2 text-sm text-gray-500">
        <%= yield %>
      </p>
    <% end %>
  </div>
</div>

app/views/shared/_flash_error_icon.html.erb
<svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
</svg>

app/views/shared/_flash_notice_icon.html.erb
<svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clip-rule="evenodd" />
</svg>

app/views/shared/_green_bubble.html.erb
<%# app/views/shared/_green_bubble.html.erb %>
<%# locals: (text:) %>
<span class="inline-flex items-center rounded-full bg-green-50 px-1.5 py-0.5 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
  <%= text %>
</span>

app/views/shared/_header_with_primary_secondary_buttons.html.erb
<div class="md:flex md:items-center md:justify-between">
  <%= render(FormHeaderComponent.new(title: title, subtitle: subtitle, description: description)) %>
  <div class="mt-5 sm:ml-10 sm:mt-4 sm:flex sm:pl-4 space-x-2">
    <%= render(SecondaryLinkButtonComponent.new(text: secondary_text, path: secondary_path)) %>
    <% if button %>
      <%= render(PrimaryButtonComponent.new(text: primary_text, path: primary_path)) %>
    <% else %>
      <%= render(PrimaryLinkButtonComponent.new(text: primary_text, path: primary_path)) %>
    <% end %>
  </div>
</div>

app/views/shared/_key.html.erb
<button 
  type="button"
  data-action="click->hidden-input#keyPress" 
  data-operation="<%= operation %>"
  class="cursor-auto h-20 w-20 sm:h-24 sm:w-24 overflow-hidden rounded-full border border-transparent bg-cyan-600 text-white text-4xl sm:text-5xl text-center shadow-sm active:bg-cyan-700 focus:outline-none focus:ring-0 active:ring-2 active:ring-cyan-500 active:ring-offset-2"
  >
  <%= number %>
</button>

app/views/shared/_navbar.html.erb
<% if @admin.nil? %>
  <nav class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="relative flex h-16 justify-between">
        <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
          <div class="sm:ml-6 sm:flex sm:space-x-8">
            <%= link_to root_path, class: "inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium hover:border-gray-300" do %>
              <div class="flex flex-shrink-0 items-baseline">
                <%= render(LogoComponent.new) %>
              </div>
            <% end %>
            <% if @current_user %>
              <%= render "shared/navbar_link", title: "Players", path: players_path %>
              <%= render "shared/navbar_link", title: "Team", path: team_path %>
              <%= render "shared/navbar_link", title: "My account", path: profile_path %>
              <% if @current_user.admin? %>
                <%= render "shared/navbar_link", title: "Admin", path: admin_path %>
              <% end %>
              <% if @impersonation_in_progress %>
                <%= link_to "Conclude impersonation", admin_impersonation_path(session[:impersonation_id]), data: { turbo_method: :delete }, class: "inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700" %>
              <% end %>
              <%= link_to "Logout", login_path, data: { "turbo-method": :delete }, class: "inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700" %>
              <% if @current_player %>
                <%= render "shared/navbar_link", title: "#{@current_player.name}'s scores", path: player_path(@current_player) %>
              <% end %>
            <% else %>
              <%= render "shared/navbar_link", title: "Login", path: new_login_path %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_progress_bar.html.erb
<%# app/views/shared/_progress_bar.html.erb %>
<%# locals: (player:, progress:) %>
<div class="ml-2 mb-1 text-xs font-bold text-gray-600 text-left">Level <%= player.level %> progress</div>
<div class="relative w-full h-6 bg-gray-600 rounded-full">
  <div class="absolute top-0 mt-1 ml-2 text-center text-white text-xs font-bold">
    <%= progress %> %
  </div>
  <div class="h-6 bg-cyan-600 rounded-full" style="width: <%= progress %>%">
  </div>
</div>

app/views/shared/_red_bubble.html.erb
<%# app/views/shared/_red_bubble.html.erb %>
<%# locals: (text:) %>
<span class="inline-flex items-center rounded-full bg-red-50 px-1.5 py-0.5 text-xs font-medium text-red-700 ring-1 ring-inset ring-red-600/10">
  <%= text %>
</span>

app/views/shared/_simple_notification.html.erb
<%# app/views/shared/_simple_notification.html.erb %>
<%# locals: (title: "Hello World!", description: "Foo bar") %>
<!-- Global notification live region, render this permanently at the end of the document -->
<div data-controller="simple-notification">
  <div aria-live="assertive" class="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6">
    <div class="flex w-full flex-col items-center space-y-4 sm:items-end">
      <!--
      Notification panel, dynamically insert this into the live region when it needs to be displayed

      Entering: "transform ease-out duration-300 transition"
        From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
        To: "translate-y-0 opacity-100 sm:translate-x-0"
      Leaving: "transition ease-in duration-100"
        From: "opacity-100"
        To: "opacity-0"
    -->
      <div data-simple-notification-target="body" class="pointer-events-auto w-full max-w-sm overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5 translate-y-0 opacity-100 sm:translate-x-0">
        <div class="p-4">
          <div class="flex items-start">
            <div class="flex-shrink-0">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-cyan-400">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 18v-5.25m0 0a6.01 6.01 0 0 0 1.5-.189m-1.5.189a6.01 6.01 0 0 1-1.5-.189m3.75 7.478a12.06 12.06 0 0 1-4.5 0m3.75 2.383a14.406 14.406 0 0 1-3 0M14.25 18v-.192c0-.983.658-1.823 1.508-2.316a7.5 7.5 0 1 0-7.517 0c.85.493 1.509 1.333 1.509 2.316V18" />
              </svg>
            </div>
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm font-medium text-gray-900">
                <%= title %>
              </p>
              <p class="mt-1 text-sm text-gray-500">
                <%= description %>
              </p>
            </div>
            <div class="ml-4 flex flex-shrink-0">
              <button data-action="simple-notification#closeNotification" type="button" class="inline-flex rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
                <span class="sr-only">Close</span>
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_team_form.html.erb
<div class="mx-auto max-w-7xl mb-4 px-4 sm:px-6 lg:px-8">
  <%= render(FormHeaderComponent.new(title: "Team", subtitle: "Teamwork makes the dream work", description: "Your team is a group of adult users who can login. Players are shared across the team.")) %>
  <%= form_with model: team, url: form_path do |form| %>
    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-4 sm:grid-cols-6">
      <div class="sm:col-span-3">
        <%= form.label :name, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <div class="mt-2">
          <%= form.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
        </div>
      </div>
    </div>
    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= render(SecondaryLinkComponent.new(text: "Cancel", path: cancel_path)) %>
      <%= form.submit "Update", class: "rounded-md bg-cyan-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-cyan-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600" %>
    </div>
  <% end %>
</div>

app/views/shared/_yellow_bubble.html.erb
<%# app/views/shared/_yellow_bubble.html.erb %>
<%# locals: (text:) %>
<span class="inline-flex items-center rounded-full bg-yellow-50 px-1.5 py-0.5 text-xs font-medium text-yellow-800 ring-1 ring-inset ring-yellow-600/20">
  <%= text %>
</span>